on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-java:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2

    - name: build dockerfile
      run: docker run -d nginx  
    - name: curl
      run: curl localhost
